name: release-tag

on:
  push:
    tags:
      - v*


jobs:
  release-image:
    name: Release latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name : install rust nightly
        run : | 
            rustup toolchain install nightly-x86_64-unknown-linux-gnu
            rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: install wasm-pack
        run: cargo install wasm-pack --force

      - name: Build
        run:  ./build.sh

      - name: Bundle
        run: tar -zcvf www.tar.gz www

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Release"
          files: |
            www.tar.gz
            README.md
            run.sh
