name: release-tag

on:
  push:
    tags:
      - v*


jobs:
  release-image:
    name: Release latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name : install rust nightly
        run : | 
            rustup toolchain install nightly-x86_64-unknown-linux-gnu
            rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: install wasm-pack
        run: cargo install wasm-pack --force

      - name: Build
        run:  wasm-pack build --release --target web --out-dir www/pkg/ --verbose

      - name: Bundle
        run: sudo rm -rf www/*.bin && cp ../port1/www/tokenizer.bin port1_tokenizer.bin && cp ../port2/www/tokenizer.bin port2_tokenizer.bin && cp ../port3/www/tokenizer.bin port3_tokenizer.bin && cp ../port4/www/tokenizer.bin port4_tokenizer.bin && cp ../port5/www/tokenizer.bin port5_tokenizer.bin && cp ../port6/www/tokenizer.bin port6_tokenizer.bin &&  tar -zcvf www.tar.gz www
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Release"
          files: |
            www.tar.gz
            README.md
