name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name : install rust nightly
      run : | 
        rustup toolchain install nightly-x86_64-unknown-linux-gnu
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run:  ./build.sh #wasm-pack build --release --target web --out-dir www/pkg/

